### ISSUE TITLE
Trouble when running examples

### ISSUE THREAD

**Issue by juliatessler** [shreyashankar/gpt3-sandbox#100]
Hi!

I'm trying to run any of the examples in the `examples` folder, but I'm stuck with the same screen that shows the default text for the UI (I uploaded an screenshot of what I got from `examples/run_latex_app.py`). Also, inputting anything there and trying to submit does nothing.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/32914231/163861529-b1430899-9114-4048-957d-fca49a54d902.png">

I have followed all the Setup steps in README and, from what I gather, the text in the UI should be different from what I see. Do you have any ideas of what I could have done wrong?

P.S.: my OpenAI console shows that my key hasn't been used. And I exported the config file as indicated in README.

**Comment by shreyashankar** [comment]
Can you post a screenshot of your terminal once the web app is launched? Are there any GET or POST requests made?

**Comment by juliatessler** [comment]
Sure! There are no other messages other than these

<img width="529" alt="image" src="https://user-images.githubusercontent.com/32914231/163870477-74e8a354-ff2d-425d-8fc0-c19cd5a1206c.png">

**Comment by shreyashankar** [comment]
Weird. If you inspect the chrome console, are there any errors?

**Comment by juliatessler** [comment]
Update: I downgrade Node to version 16 (was using 17.5) and it worked!

**Comment by shreyashankar** [comment]
Oh thank you for letting me know!
