### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by teehanming** [shreyashankar/gpt3-sandbox#111]
Browser:
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Terminal:
127.0.0.1 - - [03/Aug/2022 19:13:33] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [03/Aug/2022 19:13:36] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [03/Aug/2022 19:13:41] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [03/Aug/2022 19:13:42] "GET /favicon.ico HTTP/1.1" 404

Description:
I followed the Readme file's instructions, but I couldn't replicate the example and always ended up with this. Can anyone help me with this?

**Comment by 00-rgb** [comment]
how did you solve this
