### ISSUE TITLE
ModuleNotFoundError: No module named 'api'

### ISSUE THREAD

**Issue by KattyMan06** [shreyashankar/gpt3-sandbox#68]
Whenever I run `from api import GPT, Example, set_openai_key
` I always get this error `Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'api'` 
Even though I have already installed everything and followed the instructions properly..

**Comment by shreyashankar** [comment]
What directory are you running this command from?

**Comment by KattyMan06** [comment]
from root I beleive

**Comment by shreyashankar** [comment]
What OS are you using, and could you post a screenshot of your terminal? I just verified that it works on my end but there might be an issue on a different system

**Comment by shreyashankar** [comment]
Closing since there has not been activity.

**Comment by 00-rgb** [comment]
@shreyashankar can you help me i have the same error
