### ISSUE TITLE
I can't set the OPENAI_CONFIG Environment Variable

### ISSUE THREAD

**Issue by lmoonwolf** [shreyashankar/gpt3-sandbox#70]
I use Windows 10 and Powershell, my problem is i can't set the OPENAI_CONFIG variable, whenever i try to run an example .py, it says "The environment variable 'OPENAI_CONFIG' is not set "
I tried $env:OPENAI_CONFIG=  ,  set OPENAI_CONFIG=  but none of it works. I also tried different file path formats to point out the openai.cfg file that i created. But i had no luck.

**Comment by lmoonwolf** [comment]
I used $env:OPENAI_CONFIG='C:\path\to\file'    it works now.

**Comment by shreyashankar** [comment]
Cool thanks for informing!
