### ISSUE TITLE
Do I need to prime the model everytime I make a request to it ?

### ISSUE THREAD

**Issue by rushilchugh01** [shreyashankar/gpt3-sandbox#79]
Like, every single time I want to get something from the model, do I need to give it examples ? 

On is it possible I create pretext/profile/save the examples someplace such that I do not have to send it to the model everytime I make a request ?

Upon making a request would the examples I try and train it with prior eat up the tokens as well ?

Just a question, couldn't think of a better forum to ask. Please close if you don't find it appropriate. 

Thanks.

**Comment by shreyashankar** [comment]
I don't think you are required to give it examples, but any time you make a request, your credits are used based on how many tokens are in the response.
