### ISSUE TITLE
getting-started.md

### ISSUE THREAD

**Issue by lingthep-limbu** [shreyashankar/gpt3-sandbox#80]
sir can you please help me with this

raise RuntimeError(
RuntimeError: The environment variable 'OPENAI_CONFIG' is not set and as such configuration could not be loaded. Set this variable and make it point to a configuration file

**Comment by shreyashankar** [comment]
did you create the config file?

**Comment by lingthep-limbu** [comment]
> did you create the config file?

yes mam did that as per the folder API, any guidance will be of great help
i am learning basic python and wants to experiment vairous gpt 3 related services.

**Comment by ZKTKZ** [comment]
hey @lingthep-limbu, check out [#5 of the README.md](https://github.com/shreyashankar/gpt3-sandbox#setup)
